# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='price_index',
            field=models.FloatField(default=0.0),
        ),
    ]
