# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170701_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='longitude',
        ),
        migrations.AddField(
            model_name='itemtype',
            name='health_index',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.CharField(default='None', max_length=20),
        ),
        
        migrations.AlterField(
            model_name='onsaleitem',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='onsaleitem',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
