# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170707_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='category',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
