# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 21:24
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_itemtype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='price_index',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3),
        ),
    ]
