# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170723_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
