# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170724_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='keywords',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
