# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170724_0401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShelfItem',
            new_name='FullPriceItem',
        ),
        migrations.AlterField(
            model_name='onsaleitem',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='onsaleitem',
            name='start_date',
            field=models.DateField(),
        ),
    ]
