# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170724_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullpriceitem',
            name='barcode_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
