# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_supplieralias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieralias',
            name='alias',
            field=models.CharField(max_length=50),
        ),
    ]
