# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_supplier_other_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='logo_url',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onsaleitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
