# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20170725_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullpriceitem',
            name='brand',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onsaleitem',
            name='brand',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fullpriceitem',
            name='barcode_num',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='fullpriceitem',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
