# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20170728_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onsaleitem',
            name='discount',
        ),
        migrations.AddField(
            model_name='fullpriceitem',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fullpriceitem',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fullpriceitem',
            name='size',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fullpriceitem',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='onsaleitem',
            name='discount_type',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onsaleitem',
            name='full_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='onsaleitem',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onsaleitem',
            name='size',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onsaleitem',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
