# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20170729_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsaleitem',
            name='full_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='onsaleitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
            preserve_default=False,
        ),
    ]
