# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_onsaleitem_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsaleitem',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
